### ISSUE TITLE
Usability: add buttons or toolbar for actions

### ISSUE THREAD

**Issue by fedeb95** [toblotron/praxis-ide#5]
First of all congratulations on the project, it's a good idea. Second, it took me a while to figure out that to add a rule page I had to right click on the folder. Maybe it's just me (or the fact I haven't used prolog in a while) but I think a toolbar for actions you can do by right clicking on a folder could be useful. Or maybe just a description of actions you can do in the README.

**Comment by toblotron** [comment]
Thank you - and thanks for the suggestion! I've now added a (initially folded) section in the README.md file, where (at least the most common/ well functioning) UI-features are described.
